[pytest]
testpaths = tests
python_files = test_*.py
addopts = -q --cov=src --cov-report=term-missing
    --cov-fail-under=98
filterwarnings =
	ignore:unclosed database in <sqlite3.Connection object.*:ResourceWarning
	ignore:setDaemon\(\) is deprecated, set the daemon attribute instead:DeprecationWarning
